version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: BurgerRestAPI-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: java14user
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          memory: 128m

  redis:
    image: redis
    container_name: BurgerRestAPI-redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 512m

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: BurgerRestAPI-redisinsight
    ports:
      - "8001:8001"

