server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  data:
    mongodb:
      host: localhost
      port: 27027
      database: userdb
      username: bilge
      password: bilge!123

userservice:
  secret:
    secret-key: ${JAVA_14_SECRET_KEY}
    issuer: ${JAVA_14_ISSUER}
