server:
  port: 1919

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: ertugrulsaliher@gmail.com
    password: oxbv jmuo zeuz icyp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

