server:
  port: 9094

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  data:
    mongodb:
      host: localhost
      port: 27027
      database: orderdb
      username: bilge
      password: bilge!123


