server:
  port: 9050

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/productdb
  jpa:
    hibernate:
      ddl-auto: update


authservice:
  secret:
    secret-key: ${JAVA_14_SECRET_KEY}
    issuer: ${JAVA_14_ISSUER}




