server:
  port: 1197

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: java14user
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/categorydb
  jpa:
    hibernate:
      ddl-auto: update




